aws: &aws
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_analytics: <%= ENV["GOOGLE_ANALYTICS"] %>

development:
  <<: *default
  secret_key_base: '3eu3he3heu3hueh3uehu3heu3hueh3u'

test:
  <<: *default

staging:
  <<: *default
  <<: *aws

production:
  <<: *default
  <<: *aws
